CREATE TABLE IF NOT EXISTS USER_PROFILE (
    CONVERSATION_ID VARCHAR(36) NOT NULL,
    SUMMARY VARCHAR(16777216),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (CONVERSATION_ID)
);
